export const environment = {
  production: true,
  recordUrl: 'http://www.fullrank.top:8000/api/jjpark/record/',
  badgeUrl: 'http://www.fullrank.top:8000/api/jjpark/badge/',
  shareUrl: 'http://www.fullrank.top:8000/api/jjpark/share/',
  statUrl: 'http://www.fullrank.top:8000/api/jjpark/stat/',
  deviceCheckUrl: 'http://www.fullrank.top:8000/api/bund18/device/check/',
  deviceOnUrl: 'http://www.fullrank.top:8000/api/jjpark/device/control/on/',
  deviceOffUrl: 'http://www.fullrank.top:8000/api/jjpark/device/control/off/',
  wxloginUrl: 'http://www.fullrank.top:8000/api/jjpark/wxlogin/',
  licenseRequestUrl: 'http://www.fullrank.top:8000/api/jjpark/device/control/request',
  licenseReleaseUrl: 'http://www.fullrank.top:8000/api/jjpark/device/control/release',
  choiceReportUrl: 'http://www.fullrank.top:8000/api/jjpark/choice/report',
  domainUrl: 'http://www.fullrank.top:8000/',
};
