let imgList = [
	"./assets/gif/1.gif",
	"./assets/gif/2.gif",
	"./assets/gif/3.gif",
	"./assets/gif/4.gif",
	"./assets/gif/5.gif",
	"./assets/gif/6.gif",
	"./assets/gif/loading-page.gif",
	"./assets/H5/1-03.png",
	"./assets/H5/2-04.png",
	"./assets/H5/3-05.png",
	"./assets/H5/arrow-19.png",
	"./assets/H5/BG-05.png",
	"./assets/H5/button-19.png",
	"./assets/H5/Button_Eng_Cn.png",
	"./assets/H5/card bling-19.png",
	"./assets/H5/card cat-19.png",
	"./assets/H5/card firstclass-19.png",
	"./assets/H5/card game-19.png",
	"./assets/H5/card moon-19.png",
	"./assets/H5/card peace lover-19.png",
	"./assets/H5/cat-19.png",
	"./assets/H5/cat2-19.png",
	"./assets/H5/contents1-08.png",
	"./assets/H5/contents2-09.png",
	"./assets/H5/contents3-10.png",
	"./assets/H5/contents4-11.png",
	"./assets/H5/contents5-12.png",
	"./assets/H5/contents6-13.png",
	"./assets/H5/diamond-19.png",
	"./assets/H5/diamond2-19.png",
	"./assets/H5/dream on-19.png",
	"./assets/H5/end-15.png",
	"./assets/H5/game-19.png",
	"./assets/H5/game2-19.png",
	"./assets/H5/love-19.png",
	"./assets/H5/love2-19.png",
	"./assets/H5/space-19.png",
	"./assets/H5/space2-19.png",
	"./assets/H5/travel-19.png",
	"./assets/H5/travel2-19.png",
	"./assets/H5/wheel-14.png",
	"./assets/H5en/1-03.png",
	"./assets/H5en/2-04.png",
	"./assets/H5en/3-05.png",
	"./assets/H5en/4-06.png",
	"./assets/H5en/5-14.png",
	"./assets/H5en/6-15.png",
	"./assets/PNG Assets H5/Additonal Icons_Buttons_Images/butterfly1.png",
	"./assets/PNG Assets H5/Additonal Icons_Buttons_Images/Button_Eng_Cn.png",
	"./assets/PNG Assets H5/Additonal Icons_Buttons_Images/FerrisWheel.png",
	"./assets/PNG Assets H5/Additonal Icons_Buttons_Images/Post_Icon.png",
	"./assets/PNG Assets H5/Additonal Icons_Buttons_Images/Share_Icon_Wht.png",
	"./assets/PNG Assets H5/Additonal Icons_Buttons_Images/TapScreen_Icon.png",
	"./assets/PNG Assets H5/Category Icons/AirPlane_Icon_Col.png",
	"./assets/PNG Assets H5/Category Icons/AirPlane_Icon_Wht.png",
	"./assets/PNG Assets H5/Category Icons/Cat_Icon_Col.png",
	"./assets/PNG Assets H5/Category Icons/Cat_Icon_Wht.png",
	"./assets/PNG Assets H5/Category Icons/Diamond_Icon_Col.png",
	"./assets/PNG Assets H5/Category Icons/Diamond_Icon_Wht.png",
	"./assets/PNG Assets H5/Category Icons/GameBoy_Icon_Col.png",
	"./assets/PNG Assets H5/Category Icons/GameBoy_Icon_Wht.png",
	"./assets/PNG Assets H5/Category Icons/Heart_Icon_Blk.png",
	"./assets/PNG Assets H5/Category Icons/Heart_Icon_Col.png",
	"./assets/PNG Assets H5/Category Icons/Saturn_Icon_Col.png",
	"./assets/PNG Assets H5/Category Icons/Saturn_Icon_Wht.png",
	"./assets/PNG Assets H5/Category Screens/CatLover_Screen.png",
	"./assets/PNG Assets H5/Category Screens/Gamer_Screen.png",
	"./assets/PNG Assets H5/Category Screens/Love_Screen.png",
	"./assets/PNG Assets H5/Category Screens/Money_Screen.png",
	"./assets/PNG Assets H5/Category Screens/Space_Screen.png",
	"./assets/PNG Assets H5/Category Screens/Travel_Screen.png",
	"./assets/PNG Assets H5/Logos/DreamOn_Footer_Logo_JJ_Col_Butterfly_Hor.png",
	"./assets/PNG Assets H5/Logos/DreamOn_MainPage_Logo_JJ_Col_Butterfly_Stack.png",
	"./assets/PNG Assets H5/Logos/JJActionPark_ENG_CN_Blk.png",
	"./assets/PNG Assets H5/Logos/JJActionPark_ENG_CN_Col.png",
	"./assets/PNG Assets H5/Logos/Official_DreamOn_Logo_JJ_Blk_Butterfly_Hor.png",
	"./assets/PNG Assets H5/Logos/Official_DreamOn_Logo_JJ_Blk_Butterfly_Stack.png",
	"./assets/PNG Assets H5/Logos/Official_DreamOn_Logo_JJ_Col_Butterfly_Hor.png",
	"./assets/PNG Assets H5/Logos/Official_DreamOn_Logo_JJ_Col_Butterfly_Stack.png",
	"./assets/PNG Assets H5/Postcards/Card_Corners-01.png",
	"./assets/PNG Assets H5/Postcards/Cat_Postcard.png",
	"./assets/PNG Assets H5/Postcards/Game_Postcard.png",
	"./assets/PNG Assets H5/Postcards/Love_Postcard-01.png",
	"./assets/PNG Assets H5/Postcards/Money_Postcard.png",
	"./assets/PNG Assets H5/Postcards/Space_Postcard.png",
	"./assets/PNG Assets H5/Postcards/Travel_Postcard.png",
];
export default imgList;